### ISSUE TITLE
Build IDE redirect page for IDE deeplinks

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1008]
Context: When redirecting users from an email to a deeplink in the IDE, we need a page on to redirect the user to the IDE.

Requirements:
- When the user lands on this page, they should automatically get the browser popup confirming that they want to be redirected. Most users will interact with this. 
- The page itself should have a link that deeplinks the user to the IDE, like the "Launch meeting" button on the Zoom page
- The page itself should have the following copy: Sourcegraph logo at the top. Headline: "Launching Cody in your IDE" Subtitle: "We've redirected you to your IDE. You can also open your IDE by clicking <this link>."

I think we could probably re-use the design from this page:
![Image](https://github.com/sourcegraph/cody/assets/3654603/7dfe147b-4e8b-42e7-aa67-790f488a4d83)

Similar to:
![Image](https://github.com/sourcegraph/cody/assets/3654603/bd4c812e-9e87-43a8-be30-b84153cce96d)
![Image](https://github.com/sourcegraph/cody/assets/3654603/f0b1d822-541d-4ff4-a626-e2c3ce60b96c)

**Comment by chenkc805** [comment]
Heads up @danielmarquespt we may need a lightweight design for this.

CC: @thenamankumar@vdavid

**Comment by slimsag** [comment]
FYI Since the Cody App already implemented this before, you can just reuse the same page. All the code already exists & is still there.

Only the `requestFrom` parameter would need to change, you can just deep link into `vscode://` instead of `cody://` as we did for the app. You can also adjust the wording/design based on the URL parameter.

The relevant code is here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenCallbackPage.tsx

Also, since we already implemented a `vscode://` URL handler in the extension (also for the app earlier on, but it should be used for the auth flow today even) I think you can just reuse that too. There might be very very little work here, just adding a new URL parameter and pointing to the new URL basically.

**Comment by iskyOS** [comment]
@chenkc805 There is an existing PR from Tim that I think is a design for this page: https://github.com/sourcegraph/cody/issues/685

**Comment by danielmarquespt** [comment]
This page also has an extra design need for JetBrains and NeoVim described here: https://github.com/sourcegraph/sourcegraph/issues/56388

Happy to work on everything we need to handle on this page

**Comment by chenkc805** [comment]
Happy for us to prioritize JetBrains, NeoVim can wait if it's a nontrivial amount of work.
