### ISSUE TITLE
Introduce exclusion patterns for files that shouldn't be sent over the network

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1049]
Cody should exclude .env files and other files that may contain secrets from being sent over the network.

One potential solution here is to exclude files that aren't part of the Git repository.

Customer requests:
* https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694539385641899
* https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1694591949182719?thread_ts=1694539385.641899&cid=C04MSD3DP5L

**Comment by jdorfman** [comment]
More requests: https://github.com/sourcegraph/cody/discussions/14

**Comment by abeatrix** [comment]
10/18 RFC create, pending for review - https://docs.google.com/document/d/15XJnQ-qa-Y3SM2eltuKfuESmgYYfx7JhEdi2447YF_0/edit?usp=sharing

**Comment by beyang** [comment]
@DanTup @abeatrix what's the latest status on this? Still to be done?

**Comment by DanTup** [comment]
I think Beatrix was/is working on supporting multi-folder workspaces but I don't know if it's complete yet. The current PR is at https://github.com/sourcegraph/cody/pull/1382 but looks like it has a bunch of merge conflicts now that will need resolving.

**Comment by abeatrix** [comment]
The work was done in the linked PR, including working with milti root repo and nest repo, and was waiting for Cody strat team to confirm but then became stale because it was implemented before simple chat was introduced and doesn't work with bfg yet. We will have to pick it back up after GA as we discussed in one of our product meetings @kalanchan
