### ISSUE TITLE
[VS Code] - Release v0.14 Test Plan

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#1195]
This test plan template aims to provide a framework for VS Code engineers to thoroughly walkthrough their changes for the v0.14 release. Each feature should include steps taken for functional, integration, usability and performance testing. Engineers can copy this template and fill out relevant sections with test cases, expected behavior and results to produce a complete test plan. 

**Note: Not all steps in the test plan may be applicable, please use it as a rough guideline of what needs to be included.**

# Commands
Commands to be covered: `/doc` `/explain` `/test` `/smell` `custom-commands`

**Test Plan:** 
- Describe the expected behaviour of your feature
- Describe the steps you've done to ensure that the feature works, see [Test Plan examples](https://github.com/sourcegraph/pr-faqs/tree/main/examples)
- Describe any caveats or special edge cases the user might experience

**QA Checklist:**

1. The feature/change has been added to the [CHANGELOG](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md)
   - [ ] Yes
   - [ ] No
2. Feature/Change has been thoroughly tested for regression and bugs.
   - [ ] Yes
   - [ ] No
3. Please provide any additional testing you've done that has not been covered above:

DRI sign off: 

# Completions
Topics to be covered: Completion UX and quality improvements

**Test Plan:** 
- Describe the expected behaviour of your feature in this release
- Describe the steps you've done to ensure that the feature works, see [Test Plan examples](https://github.com/sourcegraph/pr-faqs/tree/main/examples)
- Describe any caveats or special edge cases the user might experience

**QA Checklist:**

1. The feature/change has been added to the [CHANGELOG](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md)
   - [ ] Yes
   - [ ] No
2. Feature/Change has been thoroughly tested for regression and bugs.
   - [ ] Yes
   - [ ] No
3. Please provide any additional testing you've done that has not been covered above:

DRI sign off: 

# Onboarding Improvements
Topics to be covered: Onboarding improvements and flow

**Test Plan:** 
- Describe the expected behaviour of your feature in this release
- Describe the steps you've done to ensure that the feature works, see [Test Plan examples](https://github.com/sourcegraph/pr-faqs/tree/main/examples)
- Describe any caveats or special edge cases the user might experience

**QA Checklist:**

1. The feature/change has been added to the [CHANGELOG](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md)
   - [ ] Yes
   - [ ] No
2. Feature/Change has been thoroughly tested for regression and bugs.
   - [ ] Yes
   - [ ] No
3. Please provide any additional testing you've done that has not been covered above:

DRI sign off: 

# Fixup
Topics to be covered: Fix up (/fix) and inline improvements

**Test Plan:** 
- Describe the expected behaviour of your feature in this release
- Describe the steps you've done to ensure that the feature works, see [Test Plan examples](https://github.com/sourcegraph/pr-faqs/tree/main/examples)
- Describe any caveats or special edge cases the user might experience

**QA Checklist:**

1. The feature/change has been added to the [CHANGELOG](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md)
   - [ ] Yes
   - [ ] No
2. Feature/Change has been thoroughly tested for regression and bugs.
   - [ ] Yes
   - [ ] No
3. Please provide any additional testing you've done that has not been covered above:

DRI sign off:

**Comment by philipp-spiess** [comment]
# Completions
Topics to be covered: Completion UX and quality improvements

**Test Plan:** 

## Single-line completions

1. Paste the following text into the editor `// Print hello world\nconsole.log`
2. You expect a completion for the current line
    <img width="465" alt="Screenshot 2023-10-03 at 14 03 03" src="https://github.com/sourcegraph/cody/assets/458591/5d859a69-03c4-47d0-a3c6-3b6c6116cf1f">

## Multi-line completions

1. Paste the following text into the editor `function bubbleSort(`
2. Expect a completion for the next lines
   <img width="833" alt="Screenshot 2023-10-03 at 14 07 40" src="https://github.com/sourcegraph/cody/assets/458591/fefc3285-ffb1-422d-8938-7083452c1929">


## Infilling

1. Paste the following text into the editor and trigger a completion at the `|` character: `// |\nconst isEnabled = checkIfWebviewEnabled()`
2. Expect a completion like this:
     <img width="1040" alt="Screenshot 2023-10-03 at 14 08 45" src="https://github.com/sourcegraph/cody/assets/458591/19c81f6d-522b-4a77-9a82-ba09f18f08a6">

## Completion widget interop
1. Type `console.` in the editor
2. Expect no completion to show up because the first item selected by VS Code is `Console` which is not correct.  
      <img width="750" alt="Screenshot 2023-10-03 at 14 09 54" src="https://github.com/sourcegraph/cody/assets/458591/c2992479-d3b7-4b07-b374-eb076436e540">
3. Select `dir` in the dropdown menu
4. Expect a completion starting with `console.dir`
     <img width="932" alt="Screenshot 2023-10-03 at 14 10 25" src="https://github.com/sourcegraph/cody/assets/458591/e56b3420-f1bf-42ac-9a02-0fb99bb58d6f">

## Error handling

1. Heavily decrease your rate limit on dotcom using the site admin access
2. Trigger completions until you hit said quota
3. Expect the bottom Cody icon to be yellow
4. When clicking that icon, expect an error text like this
     <img width="980" alt="Screenshot 2023-10-03 at 14 11 31" src="https://github.com/sourcegraph/cody/assets/458591/3da226ef-c925-4a24-acac-aa92272beb1e">


## Manual completion trigger

1. Paste the following into the document `console.log(`
2. Expect a completion to show up
3. Now tab out of the window and back in. The completion is now no longer visible
4. Use alt+\ to trigger a manual completion
5. Expect the completion to be visible again
    <img width="1294" alt="Screenshot 2023-10-03 at 14 14 45" src="https://github.com/sourcegraph/cody/assets/458591/77cf0ed9-eac7-4f04-818b-f5ce16895352">


**QA Checklist:**

1. The feature/change has been added to the [CHANGELOG](https://github.com/sourcegraph/cody/blob/main/vscode/CHANGELOG.md)
   - [x] Yes
   - [ ] No
7. Feature/Change has been thoroughly tested for regression and bugs.
   - [x] Yes
   - [ ] No
8. Please provide any additional testing you've done that has not been covered above:
  - All features were added as A/B experiments and we heave measured their effects on CAR and latencies

DRI sign off: @philipp-spiess
