### ISSUE TITLE
Clean up app-optional onboarding code

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1229]
Requirements:
- Remove any experiment code
- Remove old code that supported the old flow (tech debt cleanup)

**Comment by dominiccooney** [comment]
We can do this after Oct 4.

**Comment by dominiccooney** [comment]
We currently put web users on classic onboarding. Making Cody VScode work well on web is a larger topic, but the specific things which don't work with simplified onboarding:

- The app setup prompts don't make sense because Cody App doesn't work with VScode web because we can't talk to localhost or the filesystem; the App &rarr; VScode redirect doesn't work with VScode web.
- dotcom redirects need to accept a redirect URL instead of hard-coding CODY or CODY_INSIDERS &rarr; vscode://sourcegraph.cody-ai or vscode-insiders://... links. Cody VScode needs to generate that URL.

Note, you *can* sign in on web with Simplified Onboarding using "Sign In to Enterprise Instance", URL and access token, and enter https://sourcegraph.com .

Best path forward:
- Do not display the Cody App toasts on VScode web.
- Make the social login buttons work with VScode web redirects.
- Make app also use simplified onboarding and delete classic onboarding.

**Comment by chenkc805** [comment]
@chenkc805 to understand how many people use VSCode in the web vs in the stand-alone app

**Comment by dominiccooney** [comment]
I've made a change in #1399 so that VScode Web can log in, but I'm not going to bother hiding the App setup toasts for Web. We don't *really* support web, and those toasts will go change anyway when we remove App.
