### ISSUE TITLE
Cody: Apply fixups by default

### ISSUE THREAD

**Issue by umpox** [sourcegraph/cody#1407]
Fixups should apply by default. We should provide the codelens options:
- "Done" -> (Hide codelens)
- "Diff"
- "Edited by Cody" -> non-clickable

Undo/Revert should be possible using normal undo flow

**Comment by toolmantim** [comment]
I put together a design for this @umpox, including the ability to retry with an updated prompt:

https://www.figma.com/file/kcXB8qZDpOGqWImwuvX6yq/Auto-applied-edits%2C-retryable-w%2F-new-updated-prompt?type=design&node-id=0-1&mode=design

It does include the idea of "Undo" and "Retry". Retry allows you to redo the prompt and try again.

The way it's designed, "Retry" does an undo then reattempts the edit with the new prompt, which is what a lot of other code AI tools are doing. But if it's not possible to implement "Undo" at all, we could have "Retry" just edit over the top, and I think the UI labelling still works.

> "Edited by Cody" -> non-clickable

I think every code lens action has to map to an action and be clickable.

Instead of "Diff" we can make the first "Edits Applied" action show the diff instead. That would be slightly less discoverable, but the diff view isn't great to use, and most people have a git diff too… so I think that's the right balance?

**Comment by umpox** [comment]
@toolmantim Thanks, will update some things!
