### ISSUE TITLE
Diagnostic quickfix menu shows no "Ask Cody to fix" option

### ISSUE THREAD

**Issue by sqs** [sourcegraph/cody#1545]
In Cody in VS Code v0.15.1698592121, there is no Cody fix option here in the menu, only explain. Copilot shows a fix option.

![image](https://github.com/sourcegraph/cody/assets/1976/8d20a102-49c7-4d29-8c75-271d7394c536)

**Comment by deepak2431** [comment]
@umpox I think that this issue only happens when there are other coding assistants with similar Code Actions. As I don't have the Co-pilot installed, the Ask Cody To Fix Options works fine.

**Comment by umpox** [comment]
I couldn't find a clear reason this could happen, but I did notice that the previous code actions were implicitly tied to other logic in VS Code (`FixupViewProvider`). I have refactored this so that code actions are registered independently: https://github.com/sourcegraph/cody/pull/1724

Haven't been able to replicate this so will close the issue. Happy to reopen if we can reproduce still!
