### ISSUE TITLE
Implement a request_id that links together autocomplete and chat/command client-side events with gateway events

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1559]
Doc with requirements and context: https://docs.google.com/document/d/1V5MK_SI7OnvzVSi1AnhuX5RzvIZTNIZ3MdHACTBz0tE/edit

**Comment by chenkc805** [comment]
CC: @kelsey-brown @olafurpg @bobheadxi @thenamankumar

**Comment by abeatrix** [comment]
I believe @valerybugakov will be working on that as discussed with @bobheadxi here https://sourcegraph.slack.com/archives/C05AGQYD528/p1698918633833779?thread_ts=1698843911.402679&cid=C05AGQYD528

**Comment by abeatrix** [comment]
@chenkc805  actually autocompletes might already have trace ID implemented, will defer to @valerybugakov @philipp-spiess to confirm

**Comment by vdavid** [comment]
Terminology question: could we call this `interaction_id` instead of `request_id`? The whole point is to bundle a number of things that we already call "request"-s into something new. A better name for this bundle would be "interaction" as it's an _interaction_ between the client and the back end. We (Cody PLG team) also considered "usageSomething" or "somethingFeatureUse", but the thing is, the interaction is not necessarily user-initiated (especially if we want to future-proof this), so "interaction" seems like the best terminology here.

**Comment by vdavid** [comment]
Btw, on the Cody PLG side, we're going to use this ID for usage limiting, as for Community (free) users, we'll want to impose some new monthly limits based on their feature use rather than LLM requests. (See our RFC-in-the-making [here](https://docs.google.com/document/d/1CIpWfhaoGJaRvQ_T78XY_M8rMSv6W6D5ETF0ltuGbgc/edit))

**Comment by abeatrix** [comment]
@vdavid we wanted to use interaction_id initially, but went with request_id because we can't create an interaction until we have made couple of requests under the hood for context fetching, which is funny because it's the exact same thing as what you described, but using the terms oppositely lol

**Comment by chenkc805** [comment]
Deprioritizing this from the Feb launch

**Comment by chenkc805** [comment]
I'm ok with closing this for now and revisiting later if we need to. Our current solution seems to work pretty well. Feel to re-open if anyone disagrees
