### ISSUE TITLE
Add Emacs editor extension

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/cody#158]
#### Customers that requested this

- https://github.com/sourcegraph/accounts/issues/2525

**Comment by hendi** [comment]
👍

**Comment by LeaveNhA** [comment]
C'mon guys, make it happen or let community work on it for you.

**Comment by steveyegge** [comment]
So sorry @LeaveNhA -- the Cody API is not quite stable enough yet. I don't want anyone, including myself, to put in a bunch of work and then have to re-architect it because our protocol changed. We keep madly rearchitecting it for new use cases.

I expect we will have an initial release in Q2. I do have an Emacs Cody client with autocomplete mostly working, although it hasn't been productionized with auth/login etc. Just waiting for the platform to stabilize (which is also a ball in my court).
