### ISSUE TITLE
As a billing owner on Cody Pro, I can cancel my plan and go back to the Cody Free tier

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1602]
Requirements:

- Everyone on the team plan that churned should get an email notifying them that they're back on the Cody Free tier.
- The churn event doesn't happen until the user reaches their next renewal date. They have Cody Pro access until then. 
- We will not issue refunds for customers that churn before their renewal date.

**Comment by chenkc805** [comment]
@danielmarquespt  do we have a churn flow design here?

**Comment by chrsmith** [comment]
The behavior here is all implemented, although we don't send the email yet. But that's covered in another ticket.

The behavior is:

- In the UI the user has the option to flag their subscription as cancelling at the end of the billing cycle.
- At the end of the billing cycle, the subscription will not renew and transition to the canceled state.
- We will send emails when we see the `customer.subscription.canceled` Webhooks event.
- Because the user's subscription status is 'canceled', they will be put on the free tier limits.
