### ISSUE TITLE
PRD: [VSC] Test command

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1659]
### Related Docs:

[PRD: Cody Chat and Commands](https://docs.google.com/document/d/1IcPqTETTIxJHOIP2JkE1ErFdQRbnF_mck97gUXlgzuQ/edit#heading=h.2wolyguph1ml)

### Description:

As a user, I want Cody to generate unit tests for code that I've selected. 

### Objectives:

Provide an easily discoverable, pre-packaged prompt that allows Cody to generate unit tests for code that a user has selected.

### Acceptance Criteria:
```[tasklist]
### Acceptance Criteria
- [x] In a new chat window, Cody generates code for a unit test for the selected code
- [x] The test command can be triggered from the sidebar, right-click menu, or keyboard shortcut
```

### Design Tasks:

```[tasklist]
### Design Tasks
```

### Engineering Tasks:

```[tasklist]
### Engineering Tasks
```

### After GA Tasks:

```[tasklist]
### After GA
- [ ] https://github.com/sourcegraph/cody/issues/1475
```

**Comment by kalanchan** [comment]
this is done, will confirm with Beyang

test command trigger:
![CleanShot 2023-11-07 at 14 28 54@2x](https://github.com/sourcegraph/cody/assets/51868853/1535ab50-98b9-48bb-8ae0-bad85e165cca)

generated test:
![CleanShot 2023-11-07 at 14 29 54@2x](https://github.com/sourcegraph/cody/assets/51868853/b07d5df2-a29e-40ec-a116-bad36b6ceda4)

**Comment by kalanchan** [comment]
going to change this to in progress as beatrix is working on improvements

**Comment by kalanchan** [comment]
@abeatrix can we move the improve test work to after GA? we have a bunch of PLG integration and polishing that we should focus on first

**Comment by abeatrix** [comment]
@kalanchan can we discuss this as a team in the next meeting? I talked to Beyang last week on deferring the improvement works to after GA since code freeze time is next week and there are polishing and bugs fixes I still need to work on for the next chat UI.

Does this work not limited by the code freeze? If it's not, I can help out but I think it'd be better if I can work with someone on the team on this as well, in case this is works that need more than 2 weeks which I'll be on my PTO then.

**Comment by taylorsperry** [comment]
Improvements are still in flight, but the PRD issue can be closed.
