### ISSUE TITLE
bug: Response is formatted as code block

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/cody#1853]
### Version

v0.16.0

### Describe the bug

Responses are being rendered as code blocks when the response is not code.
This happens only when the workspace is not a git repo. 
This happens only when Claude 2 is selected as the model.

https://github.com/sourcegraph/cody/assets/69164745/5dd88c24-e951-4c24-a87f-23f767ce0b54

### Expected behavior

Responses are not formatted as code unless the response is code.

**Comment by abeatrix** [comment]
Looks like a regression with Claude 2.1 as I could not reproduce the same issue when using Claude 2.0 during my debug session with @gabtorre . 

We have now set Claude 2.0 as the default chat model for VS Code instead of unpinned version Claude 2 that would use 2.1 by default: https://github.com/sourcegraph/cody/pull/1860
