### ISSUE TITLE
bug: confusing "doc" diff view

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/cody#1949]
### Version

v0.16.1

### Describe the bug

I ran the `/doc` command (from the command palette) and saw some strange behavior with both the diff view and the "Undo" action. [Loom](https://www.loom.com/share/b241d0d0a89c4e13b795522353899e8c). 
- The diff view tab calls it a "fixup" diff, but this is for the documentation command
- The diff itself doesn't show the documentation that was added, but rather a change to the code
- Clicking "undo" doesn't remove the documentation, but changes the code 

### Expected behavior

The only time I can imagine someone wanting to see a diff view of the documentation is if they're running the doc command on code that already has documentation, and that documentation is changing. So maybe not a super common use case? 

Either way, I'd expect the diff view to represent the change to the documentation and not change the documented code at all. I'd expect "undoing" the documentation to undo the documentation and not affect the code.

**Comment by taylorsperry** [comment]
Oops, one more thing I noticed. "Retry" has pretty bad UX. [Loom.](https://www.loom.com/share/f6190ed15cd44e20906a1f41585c7744) If we can't make it easier to read/edit the prompt, I think we should just remove "Retry" from the ghost text for the doc command.

**Comment by abeatrix** [comment]
Cc @umpox who's been working on the UX update for `/doc`

**Comment by umpox** [comment]
@taylorsperry Thanks for the videos!

I'm going to list the issues and the current state:
1. Diff view tab named "Fixup" -> We should change this to "Edit", then it covers all cases and makes more sense to a user.
2. The diff itself doesn't show the documentation that was added, but rather a change to the code -> Fixed in latest release (see video below)
3. Clicking "undo" doesn't remove the documentation, but changes the code -> Fixed in latest release (see video below)
4. Retry UX poor UX. -> We're quite limited here as VS Code doesn't provide a multi line input. I think we can keep it still because it still provides other functionality (users can easily delete the entire text and provide their own prompt - I've done this a few times). Users may also just want to re-submit the prompt. The "retry" field makes a lot more sense for user provided edits, like "comment this code" -> Retry -> "comment this code inline". 

https://github.com/sourcegraph/cody/assets/9516420/cc74ed2c-44a0-4ffc-a4f8-30fe9ac53fb6

**Comment by taylorsperry** [comment]
Awesome, thank you @umpox !
