### ISSUE TITLE
As a user at company @acmecorp.com, I can see other teams with team owner domain matching @acmecorp.com and request to join the team

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1953]
Requirements:
- As a Cody Free user at @acmecorp.com, I can see other teams with the team owner's domain matching @acmecorp.com and request to join the team
  - The team owner of that team can accept or reject the request to join
- For users with a personal email domain, there is no "join team" functionality. Teams with team owner with a personal email domain can only invite users to join the team, and cannot have others request to join their team.

**Comment by vdavid** [comment]
"I can see other teams with the team owner's domain matching @acmecorp.com and request to join the team" is missing, but I'd still like to close this issue because working with company domains didn't turn out to be something we care a lot about yet. When/if we choose to care about company domains, we need a thorough planning session anyway, so this is safe to close for now and recreate a slightly different issue later.
