### ISSUE TITLE
bug: Commands that require open files continue instead of stopping

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#2302]
### Version

main e75560d7d7380a662a663ed2c10bc1607c7db60b

### Describe the bug

Some commands require an open file and post unhelpful output to the transcript:

https://github.com/sourcegraph/cody/assets/153/2b23fc69-961f-40de-95b0-adcbfe885f5e

### Expected behavior

Only the native VS Code error notification is posted, and both the request and response is never added to the transcript.

**Comment by kalanchan** [comment]
following up on this - this seems to only happen if you invoke commands from the chat input and not the side panel


https://github.com/sourcegraph/cody/assets/51868853/db295441-7d9b-4051-8226-e7d1a683bc56

**Comment by DanTup** [comment]
I had a go at fixing this a couple of different ways, but they all feel bad for different reasons so I'm hoping for some pointers.

The native VS Code error message shown comes from here in the `CommandRunner`:

https://github.com/sourcegraph/cody/blob/2a00da01ae8b83ecd5450af7be2682c32edf3080/vscode/src/commands/CommandRunner.ts#L70-L74

But this code doesn't directly seem to have the ability to influence the call to the LLM. I thought maybe we should set some kind of `errorKind` flag on the command runner to indicate that it won't be able to run.

Here seems like a convenient place to read such a flag to avoid sending anything to the LLM and perhaps showing a nicer error in the chat conversation. There seems to be something similar for missing selections:

https://github.com/sourcegraph/cody/blob/2a00da01ae8b83ecd5450af7be2682c32edf3080/lib/shared/src/chat/recipes/custom-prompt.ts#L61-L63

However, at this point we only have access to the `command` (`CodyPrompt`) and not the `CommandRunner` (since `getCommand` returns only the command, and disposes the runner). Changing `getCommand()` to the runner could work, but since that interface is outside vscode/ presumably would be breaking to other editors.

Putting the `errorKind` on the command (`CodyPrompt`) instead seemed like it could work, and it did.. but it seems like that object may be reused reused (once I trigger the error, every `/smell` command fails with it, even if I've no opened the file). This seems slightly odd to me, as other properties on that class look like they're specific to each prompt.

Another thing I thought could work is if we could have the equivalent of the "selection" check above for this command (eg. check whether this command requires an active file and we don't have one), but it's not clear to me where the flags on this `contextConfig` come from (of what they really mean... `contextConfig.selection` appears to be used in this condition as if it means "we need a selection", however the the comment on the interface says "Type of context available for prompt building" so I'm unsure if it really means we _need_ this, or we _have_ this.

Not sure who has the most context around this that might be able to provide pointers (I suspect @abeatrix?).
