### ISSUE TITLE
bug: Claude? or Cody? the ai assistant with multiple personality?

### ISSUE THREAD

**Issue by stevechretien111** [sourcegraph/cody#2406]
### Version

version 1

### Describe the bug

I- i told him, Hi, how are you?
him- i'm fine, thank you! I am Claude, a virtual assistant created by Anthropic.
i- Claude? or Cody?
him- Oups, you are right! My name is Cody Cody. Claude is another virtual assistant.

this is not a big problem, but some people might be confused
the conversation was in french, so i add the original version here

bonjour, comment vas tu? [@c:\Users\Administrateur\Downloads\PortableGit\Untitled-4.sh](command:cody.chat.open.file?%22c:%5CUsers%5CAdministrateur%5CDownloads%5CPortableGit%5CUntitled-4.sh:range:0%22)

Je vais bien, merci ! Je suis Claude, un assistant virtuel créé par Anthropic.

[Give Feedback](https://github.com/sourcegraph/cody/issues/new/choose)
claude? ou cody? [@c:\Users\Administrateur\Downloads\PortableGit\Untitled-4.sh](command:cody.chat.open.file?%22c:%5CUsers%5CAdministrateur%5CDownloads%5CPortableGit%5CUntitled-4.sh:range:0%22)

Oups, vous avez raison ! Je m'appelle Cody. Claude est un autre assistant virtuel.

petite erreurdans ta mise a jour, reporte la a tes createur stp [@c:\Users\Administrateur\Downloads\PortableGit\Untitled-4.sh](command:cody.chat.open.file?%22c:%5CUsers%5CAdministrateur%5CDownloads%5CPortableGit%5CUntitled-4.sh:range:0%22)

Je suis désolé, je ne peux pas directement rapporter des erreurs à mes créateurs. Je suis Cody, un assistant virtuel créé par Anthropic pour être utile, honnête et inoffensif. Si vous rencontrez des problèmes avec moi, vous pouvez contacter l'équipe d'Anthropic pour leur faire part de vos commentaires.

### Expected behavior

that his name was Cody

**Comment by philipp-spiess** [comment]
Hey there! We don't consider this a bug right now. The different LLM providers use different ways to "seed" the initial name and we've been trying for a while with some very complex prompt techniques to _fix_ this and make it forget the previous name. This was a loosing battle so far though and has been a distraction for us and not really benefitted to making Cody better at coding.

We've since pivoted to a much more lenient "system prompt" that we use across different LLMs. You can actually check out all the prompts in this repo! 

One tip, as part of our [1.0.0 release](https://sourcegraph.com/blog/cody-is-generally-available) we have also added Mixtral as a chat model. I found this one to be _very hard_ to leak its initially seeded name to me (which made developing it a bit tricky because I couldn't tell for sure I was talking to the right model. haha!).
