### ISSUE TITLE
JetBrains: Linux is not supported

### ISSUE THREAD

**Issue by bjester** [sourcegraph/cody#244]
#### Feature request description
The Jetbrains/IntelliJ extension for Cody AI says 'Linux is not yet supported by the Cody App...' under the option to 'Use the local Cody App'. I'm currently running the Cody App on Linux, but I'm not able to select this option because it's disabled with this message.
![Screenshot from 2023-07-13 11-51-41](https://github.com/sourcegraph/sourcegraph/assets/819838/edb2eee8-41e4-4b3e-a851-a97dc95619ba)

#### Is your feature request related to a problem? If so, please describe.
Somewhat-- seems the extension perhaps isn't up-to-date with new releases of the Cody App _for Linux_

#### Describe alternatives you've considered.
I've tried 'Use sourcegraph.com' but it says it's missing the context, which I already created with the local Cody App.

#### Additional context
Ubuntu 22.04
Cody App: cody_2023.7.11+1384.7d20a90ce7_amd64.AppImage
Cody Jetbrains extension: v3.0.5

**Comment by jdorfman** [comment]
Thanks for the report @bjester. Going to let the team know.

**Comment by Gedochao** [comment]
Looking at the VS Code counterpart, it seems like there is no predefined path for the runnable of the local app on Linux, but we do have the `app.json` path there.
https://github.com/sourcegraph/cody/blob/63cd1da89b4e8d7c125c042227655d43c0e91618/vscode/src/services/LocalAppFsPaths.ts#L19

Since it might be troublesome to predict where the runnable would be installed by a particular user on a particular distro, we'd probably not have an easy to find location like on Mac.
A possible alternative would be to look on the `$PATH`.
We'd need it to confirm the app is installed on the system, as well as to be able to run it from the plugin.

We could also assume it is installed if it's running in the background, since we'd have the url from `app.json`, but it might require to rethink the plugin setup flow for Linux.

**Comment by vdavid** [comment]
@Gedochao:
- We have [this](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/services/LocalAppFsPaths.ts?L17) for VS Code, added in https://github.com/sourcegraph/sourcegraph/pull/54405.

I guess we could just add this same logic for now?
