### ISSUE TITLE
VS Code: Code suggestions always use black background 

### ISSUE THREAD

**Issue by simoncwaterer** [sourcegraph/cody#248]
I switched the VS Code theme from dark to light background. However in the Cody chat pane any sample code still has a dark background. See attached image. Should the Code snippets follow the selected theme? Code snippets in the inline chat window do use the same theme. Again see the attached image.

<img width="790" alt="image" src="https://github.com/sourcegraph/cody/assets/23657075/dac444d4-6554-4672-9a25-12f399ed55fb">

<img width="880" alt="image" src="https://github.com/sourcegraph/cody/assets/23657075/d748c3d5-1ccf-409e-a08f-94399bef9086">

**Comment by tobias-mayer** [comment]
The issue here is that the two components use a completely different pipeline for markdown to html conversion and sanitization.
The inline chat uses vscode.MarkdownString while the chat pane code is not vscode specific and uses markedjs + DOMPurify.

We will face the same problem in issue https://github.com/sourcegraph/cody/issues/41

We should probably generalize this and use one solution everywhere. Otherwise issues like this one and the one linked above will always have to be fixed in different places and for every editor plugin.

If you decide which one to use, I'm happy to provide the implementation.
