### ISSUE TITLE
As a Sourcegraph teammate, I should have a way (eg. dummy accounts) to QA the PLG paid flows

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2543]
Flows that I'd like for us to easily replicate here for QA purposes: https://docs.google.com/document/d/15wnVMbZAlU8DOXJKSWlPREaYz0Cuf-8pltips-BetsY/edit#heading=h.get2v7tig82w

**Comment by chrsmith** [comment]
Assigning to myself.

We probably won't have the ability to create "dummy accounts", but the work to do here is to document and test various test cards from Stripe (https://stripe.com/docs/testing) for validating error cases.

**Comment by vdavid** [comment]
What's missing here is:
- A config for `samsHostname` and `sscBaseUrl` on the https://cody-services-dev.sgdev.dev/ site.
- Update https://accounts.sgdev.org/cody/subscription to give the user a way to go back to /cody/manage
- Enable the feature flags for a few test users to allow them to test
- Clients have dotcom's URL hard-coded, so we won't be able to test end-to-end including the clients, but it shouldn't be a problem: client teams can test with the test users we've provided.

→ adding these to a task list above

**Comment by vdavid** [comment]
@chrsmith, do you think we can close everything else but the nav bar (second task above) today? Are we missing something else than listed?

**Comment by chrsmith** [comment]
There's lots of testing to do. So I think we should keep this ticket open, but as far as "there being a way", it should be working end-to-end on https://cody-services.sgdev.dev.

# Quick Cody PLG Testing Guide

https://cody-services.sgdev.dev has the `use-ssc-for-cody-subscription` flag flipped globally. So when you view https://cody-services-dev.sgdev.dev/cody/manage, you are seeing your subscription data from dotcom combined with the SSC backend.

⚠ Clicking "Manage" will take you to accounts.sourcegraph.com. Your subscription information for Cody-services.sgdev.dev is actually at https://accounts.sgdev.org. So you will need to be aware of this, and navigate to the other domain after you click the button in the UI.

On the SSC frontend dev instance (accounts.sgdev.org), you can use test payment methods as described in Stripe's docs. (https://stripe.com/docs/testing)

The expected behavior is that we offer a free trial until 2/15.

> NOTE: This is currently broken, and we have the free trial end on 2/10 by mistake. This will be fixed once https://github.com/sourcegraph/accounts.sourcegraph.com/pull/437 gets merged and deployed.

In order to test dunning and payment functionality, you will need to provide some overrides for the SSC frontend. In particular, within your JavaScript console, set:

```js
window.localStorage.setItem('sourcegraph.debug.always-show-new-signup', 'true')
window.localStorage.setItem('sourcegraph.cody.offer-cody-pro-free-trial', 'false')
``

After you refresh your browser, the SSC frontend will no longer offer a free trial. And the billing interval will be daily. (But you'll still need to wait 24h to automatically get charged for validating error cases unfortunately.)

If you are successful in creating a new Cody Pro trial, and want to go through the flow again, you can use the following command:

```js
window.localStorage.setItem('sourcegraph.debug.always-show-new-signup', 'true')
```

This will prompt you to sign up for a new Cody Pro subscription, even if you already have one.

⚠ This is going to do weird things on the backend, so be warned. e.g. you'll have multiple Stripe subscriptions active. So you may receive multiple emails, etc.

**Comment by andreeleuterio** [comment]
@chrsmith on the instructions above there's a typo in the URL, it should be `https://cody-services-dev.sgdev.dev/`
