### ISSUE TITLE
Cody for IntelliJ - File context is never retrieved 

### ISSUE THREAD

**Issue by baristaGeek** [sourcegraph/cody#258]
I'm using Cody for IntelliJ Idea CE and I never get context from files retrieved, which is a huge value prop for this extension (and that's why in VS Code it gives way better results). For some context, I did add my Sourcegraph access token. I'm using IntelliJ IDEA 2023.1.3 (CE) in a Mac OS 11.6.2 with Apple M1 chip. 

(IntelliJ vs VS Code results compared)

<img width="987" alt="Screen Shot 2023-07-14 at 2 57 37 PM" src="https://github.com/sourcegraph/cody/assets/8325094/242581f9-87b5-4762-bf2b-56984a18dcdc">

<img width="608" alt="Screen Shot 2023-07-14 at 2 59 37 PM" src="https://github.com/sourcegraph/cody/assets/8325094/39e041f4-18a4-4c48-a713-830bfd164ed3">

**Comment by jdorfman** [comment]
Thanks @baristaGeek reported it to the team :)

**Comment by vdavid** [comment]
Hi @baristaGeek!
Thanks for reporting this issue!
**Question:** What server are you using? Cody App, sourcegraph.com, or an Enterprise instance? We've observed this exact behavior when people used the JetBrains plugin with an Enterprise instance with a version earlier than 5.1.0. Might this be your case, and if so, does your company plan to upgrade to 5.1.0+?

If you're using the Cody App, are you, by any chance, experiencing this behavior with an open-source repo? It'd be helpful because then we could try to reproduce the behavior and investigate it further.

**Comment by baristaGeek** [comment]
Hey @vdavid, I'm using the Cody App, in a closed-source repo.
