### ISSUE TITLE
remove error banners related to context limit

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#2766]
Background context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1705357214212829?thread_ts=1705356180.305859&cid=C05AGQYD528

Suggested by Corey: Remove all banners that warns of context limit increase

**Comment by dominiccooney** [comment]
> Suggested by Corey: Remove all banners that warns of context limit increase

@chillatom I think we should look at the places in the code which "push context warnings" (code like this in DefaultPrompter/makePrompt for example):

```
            if (limitReached) {
                warnings.push('Ignored current user-specified context items due to context limit')
                return { prompt: promptBuilder.build(), contextLimitWarnings: warnings, newContextUsed }
            }
```

And decide, do we want to keep a warning for this and truncate at this point?

And second, when we have too much context all together, what truncation behavior do we want?

Here's my first cut:
- User specified context items too large in aggregate: Continue to warn. (Later, make the warning nicer about which ones we dropped.) My thinking here is we're disobeying something you *just* explicitly told us to do.
- Previous context too large: Don't warn.
- Previous transcript too large: Don't warn.

Here's the truncation behavior we have today. Include the following until the limit is reached, then truncate:
- Preamble
- Existing transcript up to current message, prioritizing recent messages (that is, current message is the most important)
- Explicit tagged context up to current message, prioritizing recent messages (that is, current tagged context is the most important)
- Current enhanced context

We should do some hand inspection of this truncation, but I think we will do better with something like:
- Preamble
- Current message
- Current explicit tagged context
- Current enhanced context (note, to this point, we are basically like "new chat" context.)
- Existing transcript *and* tagged context, prioritizing recent messages (that is, previous bot response is the most important, and tagged context is likely to be included.)

Would be cool to try having the LLM giving feedback along with its response about which context sources it found useful, and boosting the priorities of those in the replayed transcript (@rishabhmehrotra has mentioned wanting one-shot learning in the transcript, this is a little bit like that...) and obviously summarizing the existing transcript instead of truncating it.

**Comment by dominiccooney** [comment]
I have filed #2769 for more forward-looking changes to truncation and summarization.

**Comment by kalanchan** [comment]
Closing as we addressed this in multi turn chat, and working on improvements to surface context limits
