### ISSUE TITLE
feedback: do not store API token in settings.json

### ISSUE THREAD

**Issue by focusaurus** [sourcegraph/cody#2924]
### Areas for Improvement

- [ ] UI/UX
- [ ] Onboarding
- [ ] Docs
- [ ] Chat
- [ ] Commands
- [ ] Context
- [ ] Response Quality
- [X] Other

### What needs to be improved? Please describe how this affects the user experience.

I learned via a security alert email today that cody is storing its API token in my VS Code `settings.json`. Please find a better place in the filesystem to store this secret. 

### Why is this feedback important? Please describe the rationale.

I keep my settings in a dotfiles repo as many thousands of developers do in order to sync their settings across many machines. Polluting this data with secrets, application state, or cache data is a no-no. These are for settings that me as the end user configures. Your VS Code extension should find elsewhere to keep its security secrets.

### Describe the solution you'd like to see

maybe `~/.local/state/` or wherever XDG suggests.

### Additional context

Email from gitguardian: "GitGuardian has detected the following Sourcegraph Token exposed within your GitHub account"

**Comment by philipp-spiess** [comment]
@focusaurus Hey Peter! Thanks for pointing this out. I’m definitely also a person that syncs their dotfiles Saving the license key in the wrong place was something we did very early on but we have since migrated to using [secret storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage). That has happened many months ago already, which is why I’m a bit surprised to still see you run into this issue. 

One possible explanation is that you've been using Cody for many months and this just went unnoticed so far. In that case I think we should add some code to ensure we delete this for _all_ of our users. If you are a new user, could you provide some information on which OS/version you are? It

**Comment by focusaurus** [comment]
This could be old as I was in an early beta group for Cody. I'll delete it. Thanks.

**Comment by philipp-spiess** [comment]
@focusaurus Thanks for being such a vivid Cody user :) Awesome, then please remove it for now and and let us know if it turns up again.

**Comment by focusaurus** [comment]
@philipp-spiess it seems to have turned up again recently. I see `~/.config/cody-ai/config.json` now has a key `.config.accessToken`.
