### ISSUE TITLE
Autocomplete: Better integration with suggestions window

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#303]
After the latest changes by @sqs, we're already in a pretty good position. There are however a few areas where we can maybe improve:

- When we return a suggestion if the suggest widget is open, VS Code usually does not show it. But sometimes it does. It always shows Copilot's. I think it is probably due to us not giving the right range, or perhaps timing, or perhaps interaction with user settings or the `suppress` setting. I was looking through the VS Code sources to figure it out, but haven't quite fully grokked it yet. 
- Find out how `editor.inlineSuggest.suppressSuggestions` exactly changes the behavior
- When the dropdown is rendered and the user uses arrows to cycle through the suggestions, can we append this to the prompt for the LLM and display different inline completions? (We do get a callback, but what if there's already some partial code written for one option in the editor?)

**Comment by sqs** [comment]
When I set `"editor.inlineSuggest.suppressSuggestions": true` in VS Code user settings OR I use the proposed API `InlineCompletionList#suppressSuggestions`, the behavior seems to be the same—and both what we want. This is with the former:

https://github.com/sourcegraph/cody/assets/1976/659ace31-3ed9-4503-98f2-55cad59e033f

**Comment by sqs** [comment]
@philipp-spiess I think I have an experimental setting and PR that makes this work a bit better: https://github.com/sourcegraph/cody/pull/311.

After that is merged, it is still not /as/ smooth as it could be:

- Taking the actual suggest widget completion item's text into account would be a UX improvement over just taking what the user has typed into the document so far. This will require updating-in-place the text document contents based on `context.selectedCompletionInfo.range` and `context.selectedCompletionInfo.text` and then passing that to completions, and possibly fixing up the returned ranges.
- The caching has a slight delay so that after you hit TAB the first time to accept the name of the symbol from the suggest widget, Cody's inline completion briefly hides. This may only be fixable with the VS Code proposed API (inlineCompletionsAdditions) `InlineCompletionList#enableForwardStability`, though...
