### ISSUE TITLE
Enterprise users can see all the projects that their admin has given to Cody as context (including projects that are in the process of being indexed for embedding, graph, or local context)

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/cody#3040]

**Comment by taylorsperry** [comment]
Closing this because the multi-repo UX includes a list of all the projects on the instance, and then only "indexing" is keyword search. We'll continue to iterate on UX. 

<img width="615" alt="Screenshot 2024-02-20 at 2 04 12 PM" src="https://github.com/sourcegraph/cody/assets/43555476/f8dc2c3f-245b-41f0-b6c1-98c6742db010">
