### ISSUE TITLE
 P1 Fix Silent bad context results of Cody Enterprize customers

### ISSUE THREAD

**Issue by arafatkatze** [sourcegraph/cody#3163]
### Version

1.42(But this is present in other versions too)

### Areas for Improvement

- [X] UI/UX
- [x] Onboarding
- [ ] Docs
- [x] Chat
- [ ] Commands
- [x] Context
- [ ] Response Quality
- [ ] Other

### What needs to be improved? Please describe how this affects the user experience.

There is a very subtle silent failure modes of Cody that I am quite positive a ton of customers have faced and they DON'T even know that they are facing them. This failure mode exists in both Vscode and Jetbrains extensions.
It goes like this:
1. User gets on a repo
2. User assumes that because the repo is indexed(because Admin said so)
They click the enhanced context and assume the jobs done. They get a very very bizarre answer that looks like it might be useful but for the most part is completely frivolous.

Classic example(See photo). In this I query message provider as it is an important class in the cody codebase but when the repo is not connected then the results are just bizarre claude hallucinations. The user still doesn't know that Cody didn't pick up any context. Why? Because other than the response of the LLM the user has literally no way to know if the context was even gotten to Cody at all or not? The user keeps using cody and probably it takes them a while to figure out this ain't working.

### No context(The error case )
![image](https://github.com/sourcegraph/sourcegraph/assets/11155207/1249ea7d-8b0e-4384-82b9-be28e372e023)

### With context
![image](https://github.com/sourcegraph/sourcegraph/assets/11155207/6ccd1dde-61b0-44c8-b1ae-a7676ba8eb40)

[Related Thread
](https://sourcegraph.slack.com/archives/C0HMGV90V/p1707816414025529)

### Describe the solution you'd like to see

@toolmantim has already solved the design part of this problem, just needs to be implemented. This should be super easy([see comment](https://github.com/sourcegraph/cody/issues/1675#issuecomment-1937586248))

**Comment by dominiccooney** [comment]
@toolmantim , WDYT about popping the enhanced context selector open if we can't detect ANY repositories?

**Comment by toolmantim** [comment]
What does it mean to not detect any repo?

**Comment by arafatkatze** [comment]
I think he means this 
<img width="322" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/51077390-81b9-48d0-9f4e-5043143d21b9">

**Comment by dominiccooney** [comment]
Sorry for the lack of clarity. There's a two step process:

1. Given a workspace, find a git repo.
2. Given that git repo, ask the remote if it is indexed.

By "not detect any repo" I meant fail in step 1.

**Comment by kalanchan** [comment]
from EPD grooming:
- add a better way to signal to enterprise users that they have no context available
- add telemetry to understand how many users are affected

open questions:
- what is the happy path for the user to get their local repo added to remote

**Comment by dominiccooney** [comment]
Here's the "spec" of what the product does today for *enterprise.*

# A Chat's Repo Set

When chatting, your set of repos is formed this way:

1. If the chat has an "automatic repo" (see below), include it in the repo set.
2. If you set repos with the repo picker, add those ones.
3. Otherwise, if the chat had repos saved with it, add those ones.
4. Otherwise, do "Workspace Repo Detection" (see below.)

Note, when we save a chat, its repos are saved with it.

# Background: Repo Identification

To get enterprise search results, you need a set of repo IDs. This is a fundamental operation in repo set building so I'll explain it in detail here and then refer to it briefly after that. The software follows a chain like:

File &rarr; git repo &rarr; git remote &rarr; repo "name" &rarr; repo ID

File &rarr; git repo: *If* the file is in the workspace, walk up the directory tree to find a git repo. We *do* walk out of the workspace root. For example, say Bob adds /Users/bob/sourcegraph/client to the workspace and the workspace root is "client" and we scrutinize file /Users/bob/sourcegraph/client/foo.ts then we *will* detect information from git in /Users/bob/sourcegraph.

git repo &rarr; git remote: Roughly, `git remote -vv` and find the first (push) URL.

git remote &rarr; repo "name": A Sourcegraph name mangling heuristic. For example, `"git@github.com:sourcegraph/sourcegraph"` is translated to `"github.com/sourcegraph/sourcegraph"`.

repo "name" &rarr; repo ID: A GraphQL query that looks in a database on the Sourcegraph instance.

Any one of these steps can fail in the obvious ways you'd imagine. For example, file is in Perforce not git. Repo is not indexed on the Sourcegraph instance. etc.

# Workspace Repo Detection

**In the background, establish a "default repo set" this way:**
- Continuously watch the list of folders in the workspace.
- When the list of folders change, for each root folder (can be more than one; we only consider the roots and not sub-folders), do the repo identification procedure outlined earlier.
- If the folder has an ID, it goes in the default repo set.

**When any chats are open, continuously attend to the "automatic repo name" this way:**
When an editor gets focus, if there are any folders in the workspace, then:
- If the `cody.codebase` setting is set, use that repo name.
- Otherwise, if the file is in a workspace folder, do the repo identification procedure.

**When a chat session is started, set the chat session's repo set to the repos in the current default repo set.**

**When a chat session is restored, and that chat session does not have a set of repos associated with it, set the chat's repo set to the repos in the current default repo set.**

# Likely Causes of Empty Repo Sets
- VSCode workspace has no roots.
- Workspace roots aren't in git repositories.
- git repositories don't have remotes.
- git repositories have remotes, but the first remote's push URL doesn't fit the Sourcegraph heuristic.
- Repository is not indexed on the Sourcegraph instance.

# Likely Causes of "Wrong" Repo Sets
- Open file is not in the workspace.
- Open file is in the workspace, but that part of the workspace ... problems outlined above: not in a git repository, repository doesn't have remotes, first remote has a push URL name our heuristic doesn't match, repository is not indexed.

# Likely Bugs
- Repo Identification depends on the network, so YMMV under variable network conditions.

**Comment by dominiccooney** [comment]
My $0.02, why don't we...

- Implement @toolmantim 's UX improvement in #issuecomment-1949261885
- Put a red badge on the enhanced context selector if we have 0 repos to draw some attention to the problem.
- Put a diagnostic about which phase of the process broke down... somewhere. Tooltip?
- Add logging to work out the prevalence of the issue.

Product team could look into...
- What's the current practice for customers with other SCMs (p4, etc.) Is it just a name mangle to pick these up?
