### ISSUE TITLE
Design "subscription payment declined" state

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/cody#3539]
If the user is in a dunning cycle, we need to explain to the user they are and provide them with the ability to fix it. 

Part of #1600 

![image](https://github.com/sourcegraph/cody/assets/539268/74fdd884-1218-4dfe-8f97-a8f03d3fc396)

[Figma](https://www.figma.com/file/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?type=design&node-id=4283-7864&mode=design)

**Comment by chrsmith** [comment]
@rrhyne for a little more context, here's the current UX for this situation which we need to improve:

## Email Notification

Users will be notified of this situation via a "payment failure" email, such as:

<img width="524" alt="image" src="https://github.com/sourcegraph/cody/assets/4029847/a75521a4-77c1-4c79-bde7-487e9288fb2c">

## Subscription Management page

This is what the user will see if their subscription's status is "past due". (Which is to say _nothing_. We should instead have some big, yellow bar that says "yo dawg, your subscription is past due. Please update your payment method for uninterrupted service!")

<img width="999" alt="image" src="https://github.com/sourcegraph/cody/assets/4029847/94f29d16-ef71-461b-89c2-264c2e684bf4">

The only hint that their subscription is in a bad state, is that some of the invoices at the bottom of the page will have the status of "open".
<img width="984" alt="image" src="https://github.com/sourcegraph/cody/assets/4029847/32d118de-fe55-4d0d-9f1d-4ff376aae4f6">

JFYI, if the user opens one of those Invoices in the "open" status, they will be taken to a Stripe-hosted page. And there they will be able to pay the invoice directly. (Which is pretty slick.)

<img width="520" alt="image" src="https://github.com/sourcegraph/cody/assets/4029847/70e3d43e-8ade-4ef4-a47e-6061c622598d">

## What this means

Each Cody Pro subscription has a "status" field, which will have one of four values:

- "trialing", meaning the Cody Pro subscription is on a free trial. This should be made apparent somehow. e.g. a "trialing" chip or something.
- "active", meaning the subscription is in a good standing. This is the normal case.
- "canceled", meaning the user no longer has a Cody Pro subscription. And instead they are looking at their old invoice history, or be presented with the ability to reactivate/resubscribe.
- "past_due", which means the user owes us money.

A subscription will get into the past due state whenever they have an unpaid invoice. This will pretty much always arise from a subscription that was renewed for a new month of service, but there was a problem charging their credit card. (They didn't have enough money, or the card was rejected, or any number of other issues.)

When a subscription is in the past due state, the following will happen:
- New will automatically retry the failed payment several times, over the next few days. Stripe is intentionally vague about this, since they have their own logic here. But it's something like "no more than 3x attempts, spread out over a 3-day period".
- If the subscription is not paid up after those N-days, the subscription will automatically transition to the canceled state. The customer will churn, and lose access to Cody Pro.

So we want to avoid this situation where possible.

To fix this, a customer usually just needs to update their payment method on file. (e.g. add a new credit card.) Then, the next time we try to collect payment again (on the next automatic retry, sometime in the future), it will succeed. And the subscription will go back into the "active" state.

Or, the customer can now drill into the invoice, and pay it directly using Stripe's API. If successful, the subscription will transition back to an active state.

## Design Recommendation

So what I think the minimum bar is in this state, is to do something like the following:

1. Make it clear from the UI that the Subscription is in a bad state. (e.g. a big, red banner or something.)
2. Indicate that there was a problem with their last payment, and they should update their payment method.
3. (Optionally) We can direct them to an unpaid invoice, and have them pay that... however, that isn't ideal, because we want them to enter their new credit card within _our_ UI. If they pay the invoice on the Stripe-hosted page, any payment method they use (e.g. Apple Pay or something else) won't be used when the subscription's bill comes due next month...
4. (Optionally) After a user enters their payment method in this situation, we could automatically retry collecting payment for open invoices manually. (e.g. so after updating their credit card there is a ~1-2 second pause, and then the subscription would suddenly become "active".)

**Comment by vdavid** [comment]
@rrhyne has progress and he'll update this ticket with it

**Comment by vdavid** [comment]
Rob updated the description above, it's done on his part. Next step is to implement it in https://github.com/sourcegraph/cody/issues/1600
