### ISSUE TITLE
bug: Reports that Claude 3 Opus has higher frequency of early output termination

### ISSUE THREAD

**Issue by chillatom** [sourcegraph/cody#3584]
### Version

N/A

### Describe the bug

From [slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1711556618306259)
From [discord](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1711562205788289)

Let's investigate and roll any remediation into the [output sequence epic ](https://github.com/sourcegraph/cody-issues/issues/14)

Reports that Opus is terminating without completing the "thought" fully.

### Expected behavior

Cody gracefully handles early terminations or allows user to [continue chat ](https://github.com/sourcegraph/cody/issues/3583)

**Comment by PriNova** [comment]
In my experience, this happens if you give the LLM not enough room to answer fully. For example, if you constrain an LLM to only 256 output tokens, it will mostly provide only a partial answer if code is involved. Asking Claude for a full implementation of the SURF (Speeded-Up Robust Features) algorithm takes about 1302 tokens.

Cody will of course cut partially. If you want to stay within a token limit, then prepend a hidden prompt to the users prompt to only answer briefly.
