### ISSUE TITLE
bug: "There is no data provider registered that can provide view data" error is displaying in commands table

### ISSUE THREAD

**Issue by RamyaGeorge** [sourcegraph/cody#4669]
### Version

1.90

### Describe the bug

after install the "cody" extension i couldn't able to use it properly

### Expected behavior

It want to work well

**Comment by Robonnet** [comment]
Suffering the same issue here. There's a couple more on the forum. Hopefully we get some feedback on this soon. You'd do well to expand on the details though. Otherwise there's a risk that the only response you'll get is "Insufficient information to handle your ticket, please follow our guidelines on how to properly submit a bug report". I'll be sure to post back to you if I receive help before you do. Please do the same.

**Comment by Robonnet** [comment]
Cody automagically started working again this morning for me. How's it looking on your end?

**Comment by dominiccooney** [comment]
Thank you for reporting this issue. To fix this we need more details about what IDE, version, etc. you're using on what operating system so we can reproduce the error that you're seeing.
