### ISSUE TITLE
VS Code: Clicking "Open Diff" will accept the changes automatically and ghost text disappear

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#4879]
### Version

v1.26.2

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro user
3. Open any sourcecode file and select and code snippet
4. Right click to open context menu and choose `Cody > Edit Code`
5. Tell the Cody to edit code `generate documentation comment` and hit enter
6. Click on `Open Diff` to open the diff
7. Close the Diff file and check the original sourcecode file

### Observed behavior:
Clicking on `Open Diff` will automatically accept the changes

### Expected behavior

The changes shouldn't be accepted and the ghost test should show until user dismiss it by accepting or undoing the changes.

### Additional context

**Video link:**

https://drive.google.com/file/d/1dBEDM_yiXnBfIb14iRMHlnKOa3bIw0aw/view?usp=drive_link

**Comment by justinmilner1** [comment]
I believe this isn't actually a bug, but rather an intentional design. 
I agree that this is confusing, the user should explicitly agree to accept the changes at some point.

**Comment by umpox** [comment]
Yeah @justinmilner1 is right. This is intentional, unfortunately we don't have many options here due to how we have to implement the inline diff. It requires injecting whitespace, so we need to clean that up before opening the dedicated diff view. We can't re-add the whitespace easily when that view is closed as it will spam the editor with undo/redo events as you open/close the diff, which will be annoying.

A possible red flag here is that diff though, it's quite inefficient...
<img width="750" alt="image" src="https://github.com/user-attachments/assets/21bd5fe2-7f7d-42e7-9bb1-7cd899f44e79">

@jay-fibi Do you normally see diffs like this? It seems to indicate that Cody got the indentation wrong, but it seems correct as far as I can tell in that screenshot. It's unusual for the diff to be so difficult to read

**Comment by jay-fibi** [comment]
@umpox Yes, the diff is showing just like the above screenshot. Here is another instance from today's repro with v1.26.7 on Windows.
![image](https://github.com/user-attachments/assets/fa1aab6f-999f-4b8e-b151-0fa5fccda43c)

Please let me know if you require any additional info.

**Comment by jay-fibi** [comment]
![image](https://github.com/user-attachments/assets/108bb790-cf51-4651-8133-4abc0714fbee)

**Comment by umpox** [comment]
@jay-fibi This will be fixed by https://github.com/sourcegraph/cody/pull/5069

I'll close this issue now!
