### ISSUE TITLE
bug: Cannot paste URL from Edge browser as Web URL in Cody chat

### ISSUE THREAD

**Issue by dbrattli** [sourcegraph/cody#4997]
### Version

v1.26.7

### Describe the bug

Cannot paste URLs as additional context Web URLs from Microsoft Edge browser. Only the title of the page will be added and thus will not be recognized as an URL. 

<img width="616" alt="Skjermbilde 2024-07-24 kl  18 43 54" src="https://github.com/user-attachments/assets/46f6c744-b929-4297-acaf-4ef4abae1fc2">

For things to work with Edge I have to paste the URL in a buffer inside the editor and copy it again, then paste will work correctly with Cody chat since the URL has now been converted to plain text.

### Expected behavior

That I can paste web links directly from Edge and to Cody in a similar way as from e.g Safari. If I paste a link from Safari it will look like this which is correct behavior:

<img width="619" alt="Skjermbilde 2024-07-24 kl  18 43 21" src="https://github.com/user-attachments/assets/bbb053b5-5339-45b9-b9d4-9ea1611bcc09">

### Additional context

Using Microsoft Edge Versjon 126.0.2592.113 (Offisiell build) (arm64) on Mac OS X Sonoma 14.5

**Comment by PriNova** [comment]
Hello @dbrattli 

Windows changed the pasting behavior in their latest update. If you want to paste a copied text or URL, press the following key shortcut combination: 

1. SHIFT + WINDOWS + V
2. A popup appears and choose `Paste as plain Text` 

![Screenshot 2024-07-25 094057](https://github.com/user-attachments/assets/1057714c-a027-4bf2-9387-d9d6f7a2d22a)

There might be an option in Windows to change this behavior. I did not switched this off because I need sometimes the Markdown option.

Sadly, VS Code does not support this behavior within the Context popup menu.

**Comment by dbrattli** [comment]
@PriNova This is on a Mac, not Windows

**Comment by PriNova** [comment]
> @PriNova This is on a Mac, not Windows

Sorry, I overlooked this.

**Comment by dbrattli** [comment]
But I can paste the URL anywhere else within Visual Studio Code, just not for a Cody Web URL

**Comment by dbrattli** [comment]
Found some more information about the issue here:

https://support.microsoft.com/en-us/microsoft-edge/improved-copy-and-paste-of-urls-in-microsoft-edge-d3bd3956-603a-0033-1fbc-9588a30645b4

"Microsoft Edge has an improved way to copy and paste paste web URLs from the address bar into your content. This feature copies and pastes a URL as a hyperlinked title instead of as a web address."

There is a setting within Edge browser to disable this behavior, and when disabled I can now paste links to Cody as Web URL again.

**Comment by PriNova** [comment]
Nice finding @dbrattli 

Happy coding.
