### ISSUE TITLE
VS Code: Autocomplete is not working.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#5626]
### Version

v1.35.1726602245 (pre-release)

### Describe the bug

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Free/Pro user
3. Open any source code file and type anything
4. Hit `Option + \`

### Observed behavior:
Autocomplete is not working and getting following error
`command 'cody.autocomplete.manual-trigger' not found`

### Expected behavior

Autocomplete should work correctly. 

### Additional context

**Screenshot:**

![Screenshot 2024-09-18 at 7 15 08 PM](https://github.com/user-attachments/assets/39ee6759-095b-4fd5-b26a-8c9f7bfb41c5)

**Comment by dominiccooney** [comment]
I can reproduce this at ab5cf3ac0c40001d4a8a359438ba641ef451d73c

**Comment by dominiccooney** [comment]
VSCode has a shortcut to manually trigger an autocomplete, why do we use our own shortcut @valerybugakov ?

This problem arises because registering the commands is tied up with setting up the autocomplete provider; if it is not set up, the command is not registered. We have a related problem where some of the other associated commands (cody.autocomplete.inline.accepted) are registered when the autocomplete provider is set up and we attempt to RE-register them when the configuration/auth status changes.

**Comment by valerybugakov** [comment]
Looking into it.

**Comment by valerybugakov** [comment]
Going to be fixed by https://github.com/sourcegraph/cody/issues/5626. Verified on the PR's branch.

**Comment by jay-fibi** [comment]
Verified that this is fixed with build `v1.35.1727177834 pre-release`, hence closing it out.

**Comment by olejorgenb** [comment]
I still get this at 1.64.0

**Comment by nviraj** [comment]
Are we sure this is resolved? Seeing the same thing today with v1.70.3 in VSC.

![Image](https://github.com/user-attachments/assets/89dbfdec-41e8-4f97-8453-74fbf4b3c2ee)
