### ISSUE TITLE
Can't trust Cody to use the correct model

### ISSUE THREAD

**Issue by kevinjamescasey** [sourcegraph/cody#6318]
### Version

v1.48.1

### Describe the bug

I had Cody set to use a local model via Ollama. After restarting VSCode to update it, I noticed that Cody had switched to using a model called Deep Cody. This is a security issue if people are trying to avoid submitting information to remote third-party controlled servers. It would be nice if I could trust Cody to keep using the same model that I told it to use.

### Expected behavior

I expect Cody to continue using the model that I indicated should be used and not switch to other models without alerting me and getting my approval.

**Comment by PriNova** [comment]
Hey @kevinjamescasey 

That the model switches back to the default model is by design. Cody don't have an offline mode currently, but the team is evaluating how to bring that feature to Cody.

If you don't mind, you can report a feature request to our community forum at https://community.sourcegraph.com/ where the devs- and product team keeps an eye closer to it.

Thank you.
