### ISSUE TITLE
Cody commands shortcut doesn't works perfectly in the editor

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#673]
After the recent updates to the command shortcut, it is not working perfectly in the editor. It would be better to change the shortcut to open the commands window.
O.S: Mac

CC: @abeatrix @toolmantim 

https://github.com/sourcegraph/cody/assets/44617923/dd9273f3-6c75-49ee-8ce6-ec5d8c1c77df

**Comment by abeatrix** [comment]
Which command was giving you the issue?

**Comment by deepak2431** [comment]
It's [⌥C], as mentioned in the startup screen.

**Comment by abeatrix** [comment]
@deepak2431 Thanks for bringing this to our attention! I'm not able to reproduce the issue on my end, and I took a look [at the code ](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/package.json?L472)and can confirm that this should work in the editor as we are not restricting it with any "when" clause. I suspect there might be a conflict with your current keybinding, and if that's the case, you can resolve that by remapping the shortcut to any shortcuts that work for you using the [shortcut editor. ](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor) Let me know if that resolves the issue for you 🙇‍♀️

**Comment by deepak2431** [comment]
Hey @abeatrix, Thanks for looking into this. I checked my shortcut binding, which is correctly mapped to Cody AI only. The issue is that whenever I use the [⌥C] command, it converts it into a special character like` ¸`. 
![iScreen Shoter - Code - 230815134539](https://github.com/sourcegraph/cody/assets/44617923/931cdc6b-0e05-4ab0-a81d-ab3b8f4ac083)

**Comment by abeatrix** [comment]
@deepak2431 converting into a special character shouldn't block the keybinding though 🤔 does it work if you remap it to another shortcut that is not taken?

**Comment by deepak2431** [comment]
@abeatrix Not sure, but if you select a code, and try the shortcut which adds a special character, then it just replaces the selected code with it in the editor rather than opening the command window. Let me try to map it with some other binding and see, as it worked for me before when the shortcut command was `Shift+Ctrl+V`.

**Comment by arafatkatze** [comment]
https://github.com/sourcegraph/cody/assets/11155207/5ca89003-01dd-4337-8a30-e047be851fb1

@deepak2431 My version of this issue is that when I open the local instance of Cody for the first few seconds pressing [⌥C] just replace stuff with a special character but after that it actually applies the command as it should seems like some sort of loading is going behind the scenes.

**Comment by dominiccooney** [comment]
Option-C is a macOS input binding for ç/Shift-Option-C for Ç, so that's where the ç comes from.

VScode does load extensions asynchronously, and until the extension is loaded, I also get çs. We should work out why the Cody extension is so slow to load for @deepak2431 and @arafatkatze.

Step one, could you hit F1, Developer: Show Running Extensions, and give us a rundown of the extensions and their startup activation/activation times? So we can work out if this is Cody or something else competing with Cody.

**Comment by deepak2431** [comment]
@dominiccooney You are CORRECT. This is the actual cause it converts into ç, because the extension doesn't get loaded asynchronously on the editor's opening. For me, in the VSCode, the extension activation time is 275ms.
Also, you can see the runtime for other extensions I have installed in the attached SS. 

![iScreen Shoter - Code - 230817152713](https://github.com/sourcegraph/cody/assets/44617923/bf9f8525-6606-44b4-b073-076604dd4d2e)
![iScreen Shoter - Code - 230817152743](https://github.com/sourcegraph/cody/assets/44617923/68e1d8b4-a48b-4ab3-ac9a-31c1c0d0a6ac)

**Comment by arafatkatze** [comment]
@deepak2431 I am slightly confused and would love to get some clarification. My original point was that pressing  [⌥C] has two results
1. Before activation of cody extension it's showing ç because cody has yet to loaded
2. After activation of cody extension it actually runs the command 
The only difference in functionality being the latency of Cody activation. You mention that the latency of cody activation for you is 275ms. in the [screenshot](https://github.com/sourcegraph/cody/issues/673#issuecomment-1681999422) but I see in the 28 second video that the problem with shortcuts persists a lot longer than 275ms. I see it for a couple of seconds. 

So I suspect the real issue on your end is that cody extension isn't being loaded(Coz the latency timing thing doesn't add up) so that's why the shortcut ain't working. Is that it or is it something else?

**Comment by arafatkatze** [comment]
@dominiccooney I do have a lot of extensions on my vscode and my cody load time is a lot higher than other extensions. It comes out to be roughly 570ms while all the other extensions come out to be roughly within 100 ms. I think the slow load time of the extension is a separate issue  and the shortcut not working is a separate issue.

**Comment by deepak2431** [comment]
> @deepak2431 I am slightly confused and would love to get some clarification. My original point was that pressing [⌥C] has two results
> 
> 1. Before activation of cody extension it's showing ç because cody has yet to loaded
> 2. After activation of cody extension it actually runs the command
>    The only difference in functionality being the latency of Cody activation. You mention that the latency of cody activation for you is 275ms. in the [screenshot](https://github.com/sourcegraph/cody/issues/673#issuecomment-1681999422) but I see in the 28 second video that the problem with shortcuts persists a lot longer than 275ms. I see it for a couple of seconds.
> 
> So I suspect the real issue on your end is that cody extension isn't being loaded at all(Coz the latency timing thing doesn't add up) so that's why the shortcut ain't working. Is that it or is it something else?

Hey @arafatkatze, Thanks for your comments. For me, I am facing the issue in both cases when the extension is loading, and also after it's loaded successfully. So, in either case, it replaces the selected code with a special character. My suggestion would be to best update the shortcut so it doesn't have any other bindings with the shortcut key or any special character or of any other in the VSCode.

**Comment by arafatkatze** [comment]
@deepak2431 Thanks for the clarification. I would recommend trying 2 things just so I can understand your problem better. The reason I ask this is because based on my search the keybinding (Option-C) shouldn't really interfere with mac/vscode stuff. So here's two things to try just so we could understand your problem better

1. 
<img width="1244" alt="image" src="https://github.com/sourcegraph/cody/assets/11155207/8f6a16e2-a410-4509-8321-0a002c014658">

In the keyboard shortcuts double click on the shortcutkey and that gives you the ability to change it. Try to set it to Option v and then try that out right away in the editor. See if that works. 

2. Can you try changing commands here to option d and see if that works?
https://github.com/sourcegraph/cody/blob/f469aadbc00497d1db6e0555962bb360bb08e6b2/vscode/package.json#L478-L479

Run everything in debugger mode again and see if it that works in the debugger instance. There is some setup involved to make the debugger run but if you can try that it would be awesome.

Doing this can help rule out other possibilities. Thank you

**Comment by deepak2431** [comment]
Hey @abeatrix, Thanks for looking into this again. But I think that just using `Option + Any Character` has a special character binding for Mac, as replacing the command with another also adds another special character. You can check this article for reference [here](https://mackeeper.com/blog/special-characters-mac-keyboard/).

If I use `Command + Option + V`, it works perfectly.

**Comment by arafatkatze** [comment]
@abeatrix If you are good on the approach of using `Command + Option + V` then I am down to spin up a pr for this. There are a few places in the codebase where this change needs to be made and I will spin up a PR if you are cool with it.

**Comment by abeatrix** [comment]
@arafatkatze @deepak2431 Thanks for looking into this with us!  I'll defer to design (@toolmantim ) regarding switching back to `Command + Option + V`, but my finding aligns with what @arafatkatze mentioned that the keybinding shouldn't interfere with bringing the command menu up for Cody. I will take a deeper look on Monday to confirm, but in the meantime for @deepak2431 , can you try remapping it to a shortcut that works for you 🙇‍♀️

**Comment by deepak2431** [comment]
@abeatrix That sounds good, take your time with it. I will map to a new binding which works for me. 

Also, just my views it would be good to keep `Command + Option + Any Key ` as I saw the other shortcuts are using this form so just to keep consistency.

**Comment by abeatrix** [comment]
The `Option+C` shortcut should not block you from opening the command menu even if it has a special character binding, so I suspect there might be something else that is causing the issue for you. I believe remapping the shortcut to something else might be the best solution for you at the moment 🙇‍♀️ 

https://github.com/sourcegraph/cody/assets/68532117/e54f2bd1-8672-4ecb-88c6-9913f152bf91
