### ISSUE TITLE
Some output (`/search`) is not throttled; some LLM use (reranking, etc.) is throttled but should not be

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#714]
Forked from discussion in #704. After #699 is fixed so the scrolling behavior is back, that scrolling is too fast because `/search` sends a lot of content "at once."

We have "Typewriter" wired to chat clients [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@23ce972044869cbfca2cd31b20dd85293d4b1771/-/blob/lib/shared/src/chat/chat.ts?L23:28&popover=pinned) but:
- The layer that intervention happens at is wrong. For example, it sits behind the BotResponseMultiplexer for recipes. The BRM will buffer and undo some of the typewriter effect; some BRM subscribers are code and don't need a typewriter effect. For the LLM reranker, the typewriter effect will slow down the reranker.
- The effect doesn't work for search, because that doesn't use the chat client.

It would be good to move this incremental display closer to the web UI (maybe not into it, but closer to it) so that everything that a human sees uses it (and it's harmonized with the incremental Markdown handling) and things destined for machines can happen as fast as possible.

**Comment by arafatkatze** [comment]
@dominiccooney Thanks for the information. I would love to work on this issue and look deeper into this.

**Comment by dominiccooney** [comment]
@arafatkatze Super! Thanks for your help with this.

I have a diff which moves the typewriter into MessageProvider which I'll post soon—I'm just working on updating tests. This improves the Typewriter (I added a method to wait for the typewriter to finish without forcibly stopping it and getting a huge chunk) and gets it out of the reranker and keyword expander path.

I haven't integrated Typewriter with the "search" output. So you might like to crib from the improved Typewriter in my diff and integrate it there, or move the typewriter out of the MessageProvider and closer to the chat view.

**Comment by arafatkatze** [comment]
@dominiccooney Thanks a lot for such a detailed response and guidance in [this comment](https://github.com/sourcegraph/cody/pull/719#issuecomment-1683393076),
I was able to make the default typewriter work for the `search` scenario but it was obviously too fast as you had mentioned  
_What you need here will involve the typewriter "slowing down" the interaction from ContextSearch._

https://github.com/sourcegraph/cody/blob/906603537a822e19a2f87c3f813c872af5ecc73e/lib/shared/src/chat/typewriter.ts#L59-L60

Basically I wanted to change this ^ a bit and after some tweaks to the typewriter max_delay I was able to make it "slow"

https://github.com/sourcegraph/cody/assets/11155207/61bb5ba7-47ac-4279-a60e-ed8904dd3eb3

Obviously doing the case statements for search case seems hacky to me and the way that I am doing it would probably have to make the max delay somehow a function of the length of the response that I got.  Maybe for the short term it might be okay to do this but I am thinking of a better way. 

I am trying to understand how to do a refactoring to solve these things cleanly and somehow also take into account your work in [explain-two](https://github.com/sourcegraph/cody/compare/main...dpc/explain-two).

**Comment by dominiccooney** [comment]
@arafatkatze Yeah, the typewriter throttle really comes way off when there's a lot of pressure behind it. I got some feedback from @toolmantim that the typing effect would be better word-by-word anyway. So let me simplify it a bit to do that and change the heuristic to not open the throttle so much. Then the integration you've done should work well.

Don't be slowed down by what I'm suggesting in explain-two, that needs work, it may be a while.

**Comment by arafatkatze** [comment]
@dominiccooney Right now I was doing this as a clean way to typewrite. It's half finished([commit](https://github.com/sourcegraph/cody/commit/5cc76f7384ef992ec990f0425b70a122006f0a4a)) but essentially my goal was to morph the typewritter interface to support longer delaytimes or changing the algo somehow so that context search stuff also gets gracefully printed. I am happy to wait for your algo change to merge so that I can merge my stuff on top of it.

**Comment by arafatkatze** [comment]
@dominiccooney The other thing that I was thinking of but didn't pursue further was. Would it be a good idea to have some sort of a queue based system where the queue would take in all the incoming input and always "typewrite" it at the same graceful speed so that the algo doesn't have to have complex algo scenarios where the typing speed is somehow a function of 
1. Length of the input(Incase of context-search)
2. Speed of incoming input(In case of LLM buffer inflow)

The typing speed is the same but the input can wary. Obviously there are many risky race conditions that can happen with this as i tried this in my attempts [here](https://github.com/sourcegraph/cody/commit/a889bb49ba249768eed3b24906fab8bdfa258b23) doesn't work well for many reasons but I figured I would give it a shot.

**Comment by arafatkatze** [comment]
I completely understand [explain-two](https://github.com/sourcegraph/cody/compare/main...dpc/explain-two) was an experimental work but the idea of two interactions seemed very interesting. My only recommendation and you probably already thought of it anyway would be to have an interaction manager interface just to separate out the functions for getting different interactions, showing different displays and executing different cases.

**Comment by arafatkatze** [comment]
We have moved to a different API for this so I am closing this issue
