### ISSUE TITLE
Inline fix not working with multiple function

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/cody#823]
The inline fix "/fix" commands don't work with multiple functions. If I select a code block with multiple functions and give a fixup instruction, it is just applied to the first function of the selected code.

See this video for the behaviour:

https://github.com/sourcegraph/cody/assets/44617923/c4a9e76f-2560-4db2-8c94-d28ab93aa345

**Comment by abeatrix** [comment]
@deepak2431 OH I think i know what happened.

When you first clicked the + signed, the inline chat was already opened for you on line 151:
![image](https://github.com/sourcegraph/cody/assets/68532117/da23c688-d9b8-4956-a129-978571ecfbb8)


but then you clicked on line 121 again, which canceled the selection and opened a new inline chat for line 121 only, that's why it only updated the first function.

I know the vs code API is very confusing! I would recommend using the new `refactor code` in the right click menu to start inline fixup, which is wayyyyyy easier! 

![image](https://github.com/sourcegraph/cody/assets/68532117/9d645d53-8a6a-4682-bc5a-3fe738698df4)

**Comment by deepak2431** [comment]
@abeatrix Thanks for looking into this. I tried doing this with the Refactor command, and it worked fine. 

Hmm, I see the issue now. Would it be possible to remove the selection not considered for the inline fix in case of such a situation?

**Comment by arafatkatze** [comment]
In this case the range value gets reset to line number when the second time the + button is clicked
https://github.com/sourcegraph/cody/blob/1a78a3049c6547ee1929a48f8c10b90b75ccfaad/vscode/src/main.ts#L196-L209

So you see below the Start and end are basically the same thing so the only way this works is by the text prefix/suffix to generate an answer coz no "actual text" is selected

```
options.range
s {c: r, e: r}
c:
r {c: 87, e: 0}
e:
r {c: 87, e: 0}
```
There could be two ways to solve it
1. I am looking at ways in which this edge case could be  handeled by "unselecting" the previous text coz the range seems like a default property of Vscode so skate around it might be very challenging 
2. The alternative is to say an error which says something along the lines of "Nothing selected" but that might confuse the user even more. Let me think a bit about this.

**Comment by abeatrix** [comment]
> Hmm, I see the issue now. Would it be possible to remove the selection not considered for the inline fix in case of such a situation?

unfortunately that's part of the vs code API that we don't have control over, but the suggested route should solve this issue. Once the interactive API is available, we will move this logic over so this will not be an issue in the future hopefully :)
