### ISSUE TITLE
Minimum VSCode version?

### ISSUE THREAD

**Issue by jsjoeio** [sourcegraph/cody#903]
Hi cody team!

I'm trying to use Cody with code-server but it seems like the version is too old. I'm having trouble finding the minimum VSCode version Cody supports in the codebase

![image](https://github.com/sourcegraph/cody/assets/3806031/91072878-33c6-4014-bbd5-3b087ed5f3b8)

I'm wondering if you can share:
1. where this version is located?
2. any workarounds to get it working? (I could manually change the version but wondering if there is a better approach)

Thank you!

**Comment by philipp-spiess** [comment]
Hey @jsjoeio, nice to see you here :) 

We define then minimum version [here](https://github.com/sourcegraph/cody/blob/main/vscode/package.json#L93-L95) so it seems to be `1.79.0` at the moment. We do try to use the latest APIs to make the best possible experience so I do expect this to increase rather than decrease in the future.

The version you are using here (1.72) looks very outdated (it was released a year ago) so I would really recommend trying to update it (or ask coder.com to update).
